### PR TITLE
Fixed link to cjdns repo

### PR DESCRIPTION
**Pull request by dniku**

### CODE REVIEW

**Comment by Weuxel** [comment]
Thanks!

**Comment by dniku** [comment]
You will probably have to regenerate the manifest as well.

**Comment by dniku** [comment]
By the way, is there any _substantial_ difference between your ebuild and https://cgit.gentoo.org/user/emery.git/tree/net-p2p/cjdns/cjdns-16.20150604.ebuild ? I'm not very experienced at reading ebuilds.

**Comment by Weuxel** [comment]
No, in fact it is emerys ebuild. I just took it some time ago to update the egit_commit to other commits.
It is probably better to use his ebuilds, as i do not update changes in the ebuild very frequently.

**Comment by Weuxel** [comment]
I just found a small change i made, so that the ebuild builds on CPUs gcc does not  recognize.
And i install doc and contrib. Emery installs the man page and doc properly.
That seems to be all.

**Comment by dniku** [comment]
Hi, `eix` is _still_ telling me that the link contains `jdelisle`.

```
$ eix cjdns -R
* net-misc/cjdns [2]
     Available versions:  ~20150112 ~20150126 ~20150204 ~20150206 ~20150209 ~20150311 ~20150320 ~20150505 ~20150505-r1 ~20150611 {PYTHON_TARGETS="python2_7"}
     Homepage:            https://github.com/jdelisle/cjdns
     Description:         Encrypted networking for regular people.

* net-p2p/cjdns [1]
     Available versions:  ~16.20150509 {PYTHON_TARGETS="python2_7"}
     Homepage:            https://github.com/cjdelisle/cjdns
     Description:         Encrypted networking for regular people

[1] "emery" layman/emery
[2] "weuxel" layman/weuxel

Found 2 matches.
```

Do you have any idea how to fix that?

**Comment by Weuxel** [comment]
I am using emerge  for this and i am not experiencing this problem:

<pre>
$ emerge -s cjdns
  
[ Results for search key : cjdns ]
Searching...
*  net-misc/cjdns
      Latest version available: 20150611
      Latest version installed: 20150611
      Size of files: 0 KiB
      Homepage:      https://github.com/cjdelisle/cjdns
      Description:   Encrypted networking for regular people.
      License:       GPL-3
*  net-p2p/cjdns [ Masked ]
      Latest version available: 17.1
      Latest version installed: [ Not Installed ]
      Size of files: 3.827 KiB
      Homepage:      https://github.com/cjdelisle/cjdns
      Description:   Encrypted networking for regular people
      License:       GPL-3
[ Applications found : 2 ]
</pre>

But there where older ebuilds with the wrong link, which am now fixed.
Try to update the tree and then see if the problem still persists.

**Comment by dniku** [comment]
Works for me after `eix-sync`. Thanks!

**Pull request merged**
